**1. DATA FRAME**

In [11]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65),
  Risk = c("Low Risk", "High Risk", "Low Risk", "Moderate Risk", "High Risk")
)

print(students)

  Student_ID Attendance Grade          Risk
1       S001         95    90      Low Risk
2       S002         72    70     High Risk
3       S003         88    85      Low Risk
4       S004         79    77 Moderate Risk
5       S005         68    65     High Risk

**2. CREATING VARIABLE**

In [12]:
attendance <- 82
grade <- 78


attendance
grade

[1] 82

[1] 78

**3. BASIC CALCULATIONS**

In [13]:
quiz <- 85
laboratory <- 90
project <- 88
exam <- 80


weighted_final_grade <- (quiz * 0.20) + (laboratory * 0.25) + (project * 0.25) + (exam * 0.30)


weighted_final_grade

[1] 85.5

**4. USING COMPARISON OPERATION**

In [14]:
attendance <- 72
grade <- 70


attendance_below_75 <- attendance < 75
grade_below_75 <- grade < 75
attendance_at_least_75 <- attendance >= 75
grade_at_least_75 <- grade >= 75


cat("Attendance is below 75:", attendance_below_75, "\n")
cat("Grade is below 75:", grade_below_75, "\n")
cat("Attendance is at least 75:", attendance_at_least_75, "\n")
cat("Grade is at least 75:", grade_at_least_75, "\n")

Attendance is below 75: TRUE
Grade is below 75: TRUE
Attendance is at least 75: FALSE
Grade is at least 75: FALSE

**5. USING AND & OR**

In [15]:
cat("Both attendance and grade are below 75: ", attendance < 75 & grade < 75, "\n")
cat("Either attendance or grade is below 75: ", attendance < 75 | grade < 75, "\n")

Both attendance and grade are below 75:  TRUE
Either attendance or grade is below 75:  TRUE

**6. SIMPLE IF STATEMENT**

In [23]:
grade <- 80

if (grade >= 75) {
  cat("Grade => 75, PASS\n")
}

Grade => 75, PASS

**7. MULTIPLE CONDITIONS**

In [24]:
grade <- 88

if (grade >= 90) {
  classification <- "Excellent"
} else if (grade >= 85) {
  classification <- "Very Good"
} else if (grade >= 80) {
  classification <- "Good"
} else if (grade >= 75) {
  classification <- "Passed"
} else {
  classification <- "Failed"
}

cat("Grade:", grade, "-", classification, "\n")

Grade: 88 - Very Good

**8. CREATING A FUNCTION**

In [25]:
classify_grade <- function(grade) {
  if (grade >= 90) {
    classification <- "Excellent"
  } else if (grade >= 85) {
    classification <- "Very Good"
  } else if (grade >= 80) {
    classification <- "Good"
  } else if (grade >= 75) {
    classification <- "Passed"
  } else {
    classification <- "Failed"
  }
  return(classification)
}

In [26]:
example_grade <- 75
result_classification <- classify_grade(example_grade)
cat("Grade:", example_grade, "-", result_classification, "\n")

example_grade_2 <- 90
result_classification_2 <- classify_grade(example_grade_2)
cat("Grade:", example_grade_2, "-", result_classification_2, "\n")

Grade: 75 - Passed
Grade: 90 - Excellent

**9. CREATE A DATA FRAME**

In [27]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65)
)

print(students)

  Student_ID Attendance Grade
1       S001         95    90
2       S002         72    70
3       S003         88    85
4       S004         79    77
5       S005         68    65

**10. ADDING A CLASSIFICATION COLUMN**

In [28]:
students$Performance <- ifelse(
  students$Grade >= 80,
  "Good",
  ifelse(
    students$Grade >= 75,
    "Passed",
    "Failed"
  )
)

students

  Student_ID Attendance Grade Performance
1 S001       95         90    Good
2 S002       72         70    Failed
3 S003       88         85    Good
4 S004       79         77    Passed
5 S005       68         65    Failed

**11. CREATING A SIMPLE RULE-BASED SYSTEM**

In [38]:
classify_risk <- function(grade_input, attendance_input) {
  if (attendance_input < 75 & grade_input < 75) {
    return("High Risk")
  } else if (attendance_input < 85 | grade_input < 80) {
    return("Moderate Risk")
  } else {
    return("Low Risk")
  }
}

In [40]:
attendance <- 72
grade <- 70

risk_level <- ifelse(attendance < 75 & grade < 75, "High Risk", "Low Risk")

classify_risk(85,91)

[1] "Low Risk"

**12. ADD MORE RULES**

In [34]:
students$Risk <- ifelse(
  students$Attendance < 75 & students$Grade < 75,
  "High Risk",
  "Low Risk"
)

print(students)

  Student_ID Attendance Grade Performance      Risk
1       S001         95    90        Good  Low Risk
2       S002         72    70      Failed High Risk
3       S003         88    85        Good  Low Risk
4       S004         79    77      Passed  Low Risk
5       S005         68    65      Failed High Risk

**13. APPLY THE RULE TO MULTIPLE STUDENTS**

In [32]:
student_risk <- function(grade, attendance){
  if (attendance < 75 & grade < 75){
    return("High Risk")
  } else if (attendance < 85 | grade < 80) {
    return("Moderate Risk")
  } else {
    return("Low Risk")
  }
}

students$Risk <- mapply(
  student_risk,
  students$Grade,
  students$Attendance
)

students

  Student_ID Attendance Grade Performance Risk
1 S001       95         90    Good        Low Risk
2 S002       72         70    Failed      High Risk
3 S003       88         85    Good        Low Risk
4 S004       79         77    Passed      Moderate Risk
5 S005       68         65    Failed      High Risk

**14. COUNT THE RESULTS**

In [ ]:
risk_counts <- table(students$Risk)
print(risk_counts)

1. How many students are high risk?
- 2
2. How many students are moderate risk?
- 2
3. How many are low risk?
- 1
4. Which group has the largest no. of students?
- Both High and Low Risks

**15. CREATE A VISUALIZATION**

In [ ]:
risk_counts <- table(students$Risk)

barplot(
    risk_counts,
    main = "Students risk classification",
    xlab = "Risk Level",
    ylab = "Number of Students"
)

1. What does the graph show?
- The graph shows a visualization for student risk classifications.
2. Which risk category has the most students?
- Both High Risks and Low Risks has the most students.
3. What action should the university take?
- Considering the fact that there are a lot of High Risks students, the school must consider the fact that those students that are in risk of getting a failed grade would lose their chance to graduate so they must focus on improving education and how they handle students in School.

**16. ADD A RECOMMENDATION**

In [ ]:
students$Recommendation <- ifelse(
  students$Risk == "High Risk", "Immediate academic intervention",
  ifelse(students$Risk == "Moderate Risk", "Academic monitoring", "Continue regular monitoring")
)

# View updated data frame
return(students)

**17. MINI KRR SYSTEM**

In [ ]:
# Pipeline: Input -> Data -> Rules -> Reasoning -> Classification -> Recommendation
# ==========================================

# Step 1: Input & Data Definition
student_id <- "S002"
attendance <- 72
grade <- 70

# Step 2: Reasoning System (Rules Engine Function)
krr_evaluate_student <- function(student_id, attendance, grade) {

  # Rule-Based Reasoning for Classification
  if (attendance < 75 & grade < 75) {
    risk <- "High Risk"
    recommendation <- "Immediate academic intervention"
  } else if (attendance < 85 | grade < 80) {
    risk <- "Moderate Risk"
    recommendation <- "Academic monitoring"
  } else if (attendance >= 85 & grade >= 80) {
    risk <- "Low Risk"
    recommendation <- "Continue regular monitoring"
  } else {
    risk <- "Unknown"
    recommendation <- "Check data validity"
  }

  # Answer Generation
  cat("==========================================\n")
  cat("          MINI KRR SYSTEM OUTPUT          \n")
  cat("==========================================\n")
  cat("Student ID    :", student_id, "\n")
  cat("Attendance    :", attendance, "%\n")
  cat("Grade         :", grade, "\n")
  cat("------------------------------------------\n")
  cat("Classification:", risk, "\n")
  cat("Recommendation:", recommendation, "\n")
  cat("==========================================\n")
}

# Step 3: Run the System to Answer the Question
krr_evaluate_student(student_id, attendance, grade)

**18. FINAL SYSTEM**

In [ ]:
student_id <- readline("Enter Student ID: ")
attendance <- as.numeric(readline( "Enter Attendance: "))
grade <- as.numeric(readline("Enter Grade: "))

student <- function(student_id, attendance, grade) {

  if (attendance < 75 & grade < 75) {
    risk <- "High Risk"
    recommendation <- "Immediate academic intervention"
  } else if (attendance < 85 | grade < 80) {
    risk <- "Moderate Risk"
    recommendation <- "Academic monitoring"
  } else if (attendance >= 85 & grade >= 80) {
    risk <- "Low Risk"
    recommendation <- "Continue regular monitoring"
  }

cat("\nStudent ID:", student_id, "\n")
cat("Attendance:", attendance,"\n")
cat("Grade:", grade, "\n\n")
cat("Risk Level:", risk, "\n\n")
cat("Recommendation:\n")
cat(recommendation, "\n")
}

student(student_id, attendance, grade)